# Jekyll main configuration file
title: Fornax Database
description: "Compilation of public data for galaxies in the area of the Fornax Cluster"

url: # (optional) https://example.com, defaults to http://localhost:4000 in development

permalink: date

remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme
