# Jekyll main configuration file
title: S-PLUS Fornax Project (S+FP)
description: "Compilation of public data for galaxies from the Fornax Cluster in the area covered by S-PLUS"

url: # (optional) https://example.com, defaults to http://localhost:4000 in development

permalink: date

remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme

#navigation:
#  - name: "Home"
#    link: "/"
#  - name: "About"
#    link: "/about"
#  - name: "Data"
#    link: "/data"
#  - name: "Contact"
#    link: "/contact"

